### ISSUE TITLE
[question]Why a kwargs for slot is necessary?

### ISSUE THREAD

**Issue by nanoric** [Numergy/signalslot#14]
I have just read the usage wiki, seeing a kwargs for slot is mandatorily reqired.
I'm a bit OCD. Since I think writing a sigslot implement without the need of kwargs is possible, I wonder why a kwargs is necessary?
Could you spend some time to explain why?

**Comment by jpic** [comment]
Necessary to prevent from crashing but maybe not the best idea in the world, Django has that so I thought why not it's probably a good idea
