### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by TTimo** [Numergy/signalslot#15]
Can you clarify the licensing for signalslot?

There is no LICENSE file in the repository, and the python files do not carry a license header.

The pypi page for the project says GPLv3, is this correct? (it actually says "GNU General Public License v3 (GPLv3) (MIT)" which doesn't make sense?)

Would you consider relicensing MIT, or LGPL?

**Comment by Sliim** [comment]
Hi @TTimo 

signalslot was first released under GPLv3, and had been re-licensed under MIT.

So you can consider the actual license is MIT. I will add a LICENSE file and correct the setup.py classifiers to reflect the real license.

**Comment by Sliim** [comment]
released signalslot `0.1.2` which clarify the MIT license, the pypi page now display only the correct license. Thanks for your report!

**Comment by TTimo** [comment]
Thank you for clearing that up!
