### ISSUE TITLE
Is it feasible to support python 3.4?

### ISSUE THREAD

**Issue by davethecipo** [Numergy/signalslot#4]
Hello,
this library looks exactly like what I need for my current project; the only problem is that I'm using python 3.4.

I made two small changes to ``contrib/task/task.py``: I modified line 63 to

    raise e_type(e_value).with_traceback(e_traceback)

and then I changed the ``__unicode__`` magic function to ``__str__`` (as a consequence, in ``test.py`` the function ``test_unicode`` uses ``str(t)`` instead of ``unicode(t)``).

These changes are compatible with python 2.7 (I ran py.test manually because I get errors from tox; probably it's a problem on my PC).

The remaining issues with python 3.4 are related to the deprecated ``contextlib.nested`` function. As far as I can understand, it has been replaced by ``contextlib.ExitStack``. I'm not familiar enough with context managers to change this part of code though.

Please let me know if you can add support for python 3.4.

**Comment by jpic** [comment]
We are definitely open to pull requests with Python 3.4 support, Python 3 expert @madjar will surely be happy to merge it.

**Comment by jpic** [comment]
It would be good to use https://pypi.python.org/pypi/contexter as a wrapper to support both Python 2 and 3. Also, we'll need a .travis.yml update to test python3.

**Comment by davethecipo** [comment]
Could you have a look at the pull request?

**Comment by Sliim** [comment]
Thanks @davethecipo 

PR reviewed and merged, I released version 0.0.11 that includes your contribution ;)
