### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by femtotrader** [Numergy/signalslot#6]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with signalslot. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable signalslot on @Sourcegraph by going to https://sourcegraph.com/github.com/Numergy/signalslot and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by Sliim** [comment]
Hello,

it's done. The sourcegraph repository will be built after every push on the github repo :)
